In [2]:
#iris data set scikit learn

In [4]:
#LDA can be used to differentiate the species

In [6]:
from sklearn.datasets import load_iris

In [8]:
iris=load_iris()

In [10]:
type(iris)

sklearn.datasets.base.Bunch

In [13]:
print(iris.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [16]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [18]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [20]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [24]:
# scikit learn reqres to be of certain type
# features=predictors
# response=outcome
#4 requirements of scikit learn
#pass feature and response as seperate objects
# feature and resonse has to be numbers
#response=numeric in reg and class
#features=numpy array
#features and rsponse should be specific shapes.
# feature=2d. 1st d no of observations .2nd=number of attributes.
#response=1D same as 1st D of features.
#check types
print (type(iris.data)) # has to be numpy arrays
print (type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [25]:
X=iris.data
y=iris.target

In [26]:
# KNN 

In [27]:
#pick a k
# search for 5 nearest neighbour aof unknown value
# response value of 5 are tallied
 

In [29]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [30]:
#import relevant class
from sklearn.neighbors import KNeighborsClassifier

In [32]:
#instatnt iate the estimator
# create an instance of KNN class
knn=KNeighborsClassifier(n_neighbors=1)

In [34]:
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


In [36]:
#training the model using fir method
#
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [38]:
# make predictions for unknown iris
knn.predict([3,5,4,2]) # returns anumpy array

D:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

In [41]:
#passing 2 sets of features
X_new=[[3,5,4,2],[5,3,4,2]]
knn.predict(X_new)

array([2, 1])

In [42]:
#using a different value of K
knn=KNeighborsClassifier(n_neighbors=5)

In [44]:
knn.fit(X,y)
knn.predict(X_new)  #different outputs

array([1, 1])

In [46]:
#Logistic Regression- Same 4 steps 
#import
from sklearn.linear_model import LogisticRegression
#instatntiate
logreg=LogisticRegression()
#make model
logreg.fit(X,y)
#predict
logreg.predict(X_new) #different predictions

array([2, 2])