In [1]:
import numpy as np

# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])


In [14]:
def max_employment(countries, employment):
    '''
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    '''
    max_country = None      # Replace this with your code
    max_value = None   # Replace this with your code

    max_country = countries[0]      # Replace this with your code
    max_value = employment[0]   # Replace this with your code

    for i in range(len(countries)):
        if (employment[i]>max_value):
          max_value=employment[i]
          max_country=countries[i]  
    
    
    
    return (max_country, max_value)








 

In [15]:
max_employment(countries, employment)

('Angola', 75.699996949999999)

In [16]:
max_value = employment[0]
employment[1]>max_value

False

In [19]:
countries[employment.argmax()]

'Angola'

In [20]:
female_completion = np.array([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

# Male school completion rate in 2007 for those 20 countries
male_completion = np.array([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])

In [21]:
 oc=(female_completion+male_completion)/2

In [22]:
oc


array([  96.416025,  102.644275,  101.41129 ,   93.316285,  103.455575,
         98.148215,  102.35113 ,   91.77855 ,   92.835475,   89.655755,
         99.218715,   98.484275,   94.172835,  117.335125,   98.275645,
         33.04039 ,   41.905225,   90.962965,   57.08404 ,   93.06015 ])

In [23]:
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])


In [26]:
employment.std()

9.3382691136878879

In [30]:
(employment-employment.mean())/employment.std()

array([-0.31965231, -0.780123  , -0.87650077,  1.82207181, -0.03051941,
       -1.99019768,  0.30144772, -0.16973184,  0.23719615,  0.84758731,
        0.18365304,  1.00821665,  0.87971351, -0.56595055, -1.07996476,
       -0.20185762,  1.38301845, -0.03051941,  1.2545153 , -1.87240259])

In [32]:
time_spent = np.array([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])
# Days to cancel for 20 students
days_to_cancel = np.array([
      4,   5,  37,   3,  12,   4,  35,  38,   5,  37,   3,   3,  68,
     38,  98,   2, 249,   2, 127,  35
])


In [36]:
if(days_to_cancel >7):
       print("tr")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [43]:
time_spent[(days_to_cancel >7)]


array([  64.55043217,   24.2315615 ,    0.        ,    0.        ,
          0.        ,   45.18261617,  157.60454283,  133.2434615 ,
          0.        ,   26.78142417,    0.        ])

In [46]:
print(time_spent.mean())

37.9729979835


In [49]:
time_spent[days_to_cancel >7].mean()

41.054003485454537

In [51]:
(time_spent[days_to_cancel >7].mean())

41.054003485454537

In [62]:
import pandas as pd
life_expectancy_values = pd.Series([74.7,  75. ,  83.4,  57.6,  74.6,  75.4,  72.3,  81.5,  80.2,
                          70.3,  72.1,  76.4,  68.1,  75.2,  69.8,  79.4,  70.8,  62.7,
                          67.3,  70.6])

gdp_values = pd.Series([ 1681.61390973,   2155.48523109,  21495.80508273,    562.98768478,
              13495.1274663 ,   9388.68852258,   1424.19056199,  24765.54890176,
              27036.48733192,   1945.63754911,  21721.61840978,  13373.21993972,
                483.97086804,   9783.98417323,   2253.46411147,  25034.66692293,
               3680.91642923,    366.04496652,   1175.92638695,   1132.21387981])


In [63]:
variable1=life_expectancy_values
variable2=gdp_values

In [66]:
variable1.mean()
variable2.mean()

9147.879916483502

In [85]:
((variable1>variable1.mean()) & (variable2>variable2.mean())).sum()+((variable1<variable1.mean()) & (variable2<variable2.mean())).sum()

len(variable1)

20

In [90]:
employment_values = pd.Series([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])
countries = pd.Series([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])


In [93]:
countries[employment_values.argmax()]

'Angola'

In [96]:
employment_values[employment_values.argmax()]

75.699996949999999

In [99]:
countries.describe()

NameError: name 'count' is not defined

In [121]:
names = pd.Series([
    'Andre Agassi',
    'Barry Bonds',
    'Christopher Columbus',
    'Daniel Defoe',
    'Emilio Estevez',
    'Fred Flintstone',
    'Greta Garbo',
    'Humbert Humbert',
    'Ivan Ilych',
    'James Joyce',
    'Keira Knightley',
    'Lois Lane',
    'Mike Myers',
    'Nick Nolte',
    'Ozzy Osbourne',
    'Pablo Picasso',
    'Quirinus Quirrell',
    'Rachael Ray',
    'Susan Sarandon',
    'Tina Turner',
    'Ugueth Urbina',
    'Vince Vaughn',
    'Woodrow Wilson',
    'Yoji Yamada',
    'Zinedine Zidane'
])


In [108]:
'Andre Agassi',
'Barry Bonds',
'Christopher Columbus',
'Daniel Defoe',
'Emilio Estevez',
'Fred Flintstone',
'Greta Garbo',
'Humbert Humbert',
'Ivan Ilych',
'James Joyce',
'Keira Knightley',
'Lois Lane',
'Mike Myers',
'Nick Nolte',
'Ozzy Osbourne',
'Pablo Picasso',
'Quirinus Quirrell',
'Rachael Ray',
'Susan Sarandon',
'Tina Turner',
'Ugueth Urbina',
'Vince Vaughn',
'Woodrow Wilson',
'Yoji Yamada',
'Zinedine Zidane'.split(' ',25)

['Zinedine', 'Zidane']

In [122]:
len(names)

25

In [123]:
names.split(' ',25)

AttributeError: 'Series' object has no attribute 'split'

In [118]:
s = pd.Series([1, 2, 3, 4, 5])
def add_one(x):
       return x + 1
print(s.apply(add_one))

0    2
1    3
2    4
3    5
4    6
dtype: int64


In [125]:
print(reverse_names(names))

None


In [126]:
names

0             Andre Agassi
1              Barry Bonds
2     Christopher Columbus
3             Daniel Defoe
4           Emilio Estevez
5          Fred Flintstone
6              Greta Garbo
7          Humbert Humbert
8               Ivan Ilych
9              James Joyce
10         Keira Knightley
11               Lois Lane
12              Mike Myers
13              Nick Nolte
14           Ozzy Osbourne
15           Pablo Picasso
16       Quirinus Quirrell
17             Rachael Ray
18          Susan Sarandon
19             Tina Turner
20           Ugueth Urbina
21            Vince Vaughn
22          Woodrow Wilson
23             Yoji Yamada
24         Zinedine Zidane
dtype: object

In [131]:
def reverse_name(name):
  split_name=name.split(" ")
  first_name=split_name[0]
  last_name=split_name[1]
  return last_name+" , "+first_name

In [136]:
reverse_name(names[0])

'Agassi , Andre'

In [137]:
def reverse_names(names):
    return names.apply(reverse_name)

In [139]:
reverse_names(names)

0             Agassi , Andre
1              Bonds , Barry
2     Columbus , Christopher
3             Defoe , Daniel
4           Estevez , Emilio
5          Flintstone , Fred
6              Garbo , Greta
7          Humbert , Humbert
8               Ilych , Ivan
9              Joyce , James
10         Knightley , Keira
11               Lane , Lois
12              Myers , Mike
13              Nolte , Nick
14           Osbourne , Ozzy
15           Picasso , Pablo
16       Quirrell , Quirinus
17             Ray , Rachael
18          Sarandon , Susan
19             Turner , Tina
20           Urbina , Ugueth
21            Vaughn , Vince
22          Wilson , Woodrow
23             Yamada , Yoji
24         Zidane , Zinedine
dtype: object